require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.fzf-lua")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.formatter")
require("core.plugin_config.oil")
-- require("core.plugin_config.telescope")
